; Sprite lookup tables

weapon_sprites:
    dq  spr_katana_idle
    dq  spr_katana_windup_1
    dq  spr_katana_windup_2
    dq  spr_katana_swing_1
    dq  spr_katana_swing_2
    dq  spr_katana_swing_3
    dq  spr_katana_block

arm_sprites:
    dq  spr_arms_idle
    dq  spr_arms_attack_1
    dq  spr_arms_attack_2
    dq  spr_arms_attack_2
    dq  spr_arms_attack_3
    dq  spr_arms_attack_3
    dq  spr_arms_block

WEAPON_SPRITE_COUNT equ 7
